### ISSUE TITLE
Value for an address is the exact amount of REV at snapshot

### ISSUE THREAD

**Issue by isepick** [r-publishing/mainnet-genesis#6]
It appears that no calculations were done for this particular address. 

https://github.com/r-publishing/mainnet-genesis/blob/69cda0c37c14b45e67ba87e31c2dc90055de1942/wallets.txt#L13439

https://revdefine.io/#/revaccounts/1111x8CVeC6ioNXgZwRTJAH3A1b6spKaKAME2J7eahHfyWeU2b1k7

**Comment by Bill-Kunj** [comment]
This is the correct figure.
https://github.com/r-publishing/mainnet-genesis/blob/69cda0c37c14b45e67ba87e31c2dc90055de1942/wallets.txt#L13439 contains the contents of the snapshot from the RChain mainnet rounded to 6-digit precision (used by RPC)  instead of 8-digit precision (used by RChain).
If you are looking for the amount of the expected RPC airdrop, the number will be in https://github.com/r-publishing/mainnet-genesis/blob/master/rpc.wallets.txt (also in 6-digit precision)

**Comment by isepick** [comment]
I was looking for the amount of the airdrop in the wrong file.
